### ISSUE TITLE
`cargo test` fails

### ISSUE THREAD

**Issue by talliberman** [frida/frida-rust#57] opened 2022-08-28 17:09 UTC
`cargo test` fails on `main` even after the changes in 82804f42322dda8603516d03525c9a2ec46d93c5 and 71be15f37a68fa0072fd4f82b0d649284b0577d7
To reproduce:
```
$ sudo docker run --rm -ti --entrypoint /bin/bash ubuntu
# apt update
# apt -y install curl clang git pkg-config libssl-dev
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.rs && sh /tmp/rustup.rs -y
# source "$HOME/.cargo/env"
# git clone https://github.com/frida/frida-rust.git
# cd frida-rust
# cargo test --features auto-download --features invocation-listener
...
   Compiling capstone v0.11.0
warning: Frida gum devkit not found, downloading from https://github.com/frida/frida/releases/download/15.2.2/frida-gum-devkit-15.2.2-linux-x86_64.tar.xz...
   Compiling frida-gum v0.8.1 (/frida-rust/frida-gum)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcMdgm8e/symbols.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.15dd5yvh2rgng99v.rcgu.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.1rvbx14yg46olqvc.rcgu.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.354nccdb7dl74v51.rcgu.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.40y402csrsey4m22.rcgu.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.4jm7uagmwv5rplw8.rcgu.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.5f7ygf2sjh9qiaz5.rcgu.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.l2hgein05500qdq.rcgu.o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c.1pw2e05btdj0hkka.rcgu.o" "-Wl,--as-needed" "-L" "/frida-rust/target/debug/deps" "-L" "/frida-rust/frida-gum-sys" "-L" "/frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out" "-L" "/frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out" "-L" "/frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lfrida-gum" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lpthread" "-Wl,-Bstatic" "-Wl,--whole-archive" "-levent_sink" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "-linvocation_listener" "-Wl,--no-whole-archive" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-50b9616eedb811b7.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-754da76e30d40e26.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-abff7c50c58df25c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-89f1a8c8e39f4a91.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-8f1929c73c3f8167.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e359d865975ccf21.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-b886fd10c5a7c7c0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-9d7c322d48daa475.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-08ae1606a951cabe.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-682a81c4b2133b72.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-a73b3512c88de071.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-7b5ec4c918d9f957.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-65c63cf3af0af657.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-4a53f0a2785abc6a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-868e2d515c28d027.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-394ad2d73aede76a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-19c77e4dc3dcb87e.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-fb44a42088c9369a.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-61a7402e61a5b0e0.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-63f8356c87a0d0e8.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-a506e577d917828c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-fc1fb63210fdafad.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-c21be34a5cae8449.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/frida-rust/target/debug/deps/frida_gum_sys-4d322fb27616b05c" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out/libfrida-gum.a(.._glib_gtrace.c.o): in function `g_trace_mark':
          /worker/frida-manylinux-x86_64/build/build/fs-tmp-linux-x86_64/glib/../../../deps/glib/glib/gtrace.c:98: multiple definition of `_frida_g_trace_mark'; /frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out/libfrida-gum.a(gtrace.c.o):/worker/frida-manylinux-x86_64/build/build/fs-tmp-linux-x86_64/glib/../../../deps/glib/glib/gtrace.c:98: first defined here
          /usr/bin/ld: /frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out/libfrida-gum.a(.._glib_gtrace.c.o): in function `g_trace_define_int64_counter':
          /worker/frida-manylinux-x86_64/build/build/fs-tmp-linux-x86_64/glib/../../../deps/glib/glib/gtrace.c:147: multiple definition of `_frida_g_trace_define_int64_counter'; /frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out/libfrida-gum.a(gtrace.c.o):/worker/frida-manylinux-x86_64/build/build/fs-tmp-linux-x86_64/glib/../../../deps/glib/glib/gtrace.c:147: first defined here
          /usr/bin/ld: /frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out/libfrida-gum.a(.._glib_gtrace.c.o): in function `g_trace_set_int64_counter':
          /worker/frida-manylinux-x86_64/build/build/fs-tmp-linux-x86_64/glib/../../../deps/glib/glib/gtrace.c:177: multiple definition of `_frida_g_trace_set_int64_counter'; /frida-rust/target/debug/build/frida-gum-sys-efbc75af0c2417a1/out/libfrida-gum.a(gtrace.c.o):/worker/frida-manylinux-x86_64/build/build/fs-tmp-linux-x86_64/glib/../../../deps/glib/glib/gtrace.c:177: first defined here
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

The following warnings were emitted during compilation:

warning: Frida gum devkit not found, downloading from https://github.com/frida/frida/releases/download/15.2.2/frida-gum-devkit-15.2.2-linux-x86_64.tar.xz...

error: could not compile `frida-gum-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
warning: Frida core devkit not found, downloading from https://github.com/frida/frida/releases/download/15.2.2/frida-core-devkit-15.2.2-linux-x86_64.tar.xz...
```

**Comment by meme** [comment] 2022-08-29 22:01
Perhaps this is a Frida issue, I cannot reproduce it on macOS. @oleavr

**Comment by meme** [comment] 2022-10-23 17:12
Going to close this as we've made quite a few related changes since. If you are still experiencing this issue, please file an issue. Thanks.

**Closed by meme** 2022-10-23 17:12 UTC
