### ISSUE TITLE
undefined symbol: __aarch64_swp4_sync on ubuntu - arm64 since Frida 16

### ISSUE THREAD

**Issue by t4lz** [frida/frida-rust#69] opened 2022-10-24 09:27 UTC
I'm getting this error after the update to Frida 16 (`frida-gum 0.9`, but from [that branch](https://github.com/frida/frida-rust/pull/68), because otherwise it cannot build on linux-arm64). I've also seen this error before, when at some point I tried to use `frida-gum 0.8` without  `auto-download` and downloaded the lib+header of Frida 16 instead of 15.

This is what it looks like:
```
root@7208b8efa450:~/going/going/hooks# LD_PRELOAD="target/debug/libhooks.so" ../go-target/go-target
../go-target/go-target: symbol lookup error: target/debug/libhooks.so: undefined symbol: __aarch64_swp4_sync
```

The target code and the hooking lib can both be found in [this repo](https://github.com/t4lz/going).

I do not get this error with `frida-gum 0.8`.

**Comment by oleavr** [comment] 2022-10-24 17:55
The issue is that Frida's Linux devkits are now built using GCC 12.2, which means they reference libgcc symbols that may be too new on some systems. I suppose we can either downgrade GCC in https://github.com/frida/docker-images, or have our CI include its libgcc.a in the devkit. Not sure if either is a good idea. Food for thought.

**Comment by aviramha** [comment] 2022-10-31 09:25
@oleavr What GCC version can we downgrade to? I think including libgcc.a might be problematic with different macros/symbols that can mix..

**Comment by meme** [comment] 2022-10-31 22:03
I'll close this as since the Frida Docker builder images have downgraded to GCC 7, the next Frida release will have this fix.

**Closed by meme** 2022-10-31 22:03 UTC
