### ISSUE TITLE
Frida-rust links multiple versions of capstone.

### ISSUE THREAD

**Issue by WorksButNotTested** [frida/frida-rust#81] opened 2023-02-03 09:19 UTC
After a long debugging session of LibAFL, it was discovered that Stalker was not working correctly as a result of being linked against multiple different versions of capstone. https://github.com/AFLplusplus/LibAFL/issues/1018. One version was as a result of dependency on the `capstone-rs` crate and the other as a result of linking against the `frida-gum-devkit` of which capstone is an embedded component (indeed it is built from a FRIDA hosted fork of the `next` branch of capstone). Frida-rust also makes use of `capstone-rs` and also introduces the same version conflict in its own right. 

The proposed solution (which has also been tested in LibAFL) is to substitute the `capstone-rs` crate with a fork (https://github.com/domenukk/capstone-rs) built using FRIDA's fork of capstone so that the versions match. Given that `frida-rust`, and the native FRIDA fork of capstone are both hosted by FRIDA in github, it seems that this would be a natural place for this fork of `capstone-rs` to be hosted also. I've discuss this approach with @oleavr and he seems in agreement, though obviously happy to discuss if you think there is a better option.

The suggested fix is therefore:

- Host the `capstone-rs` fork above in FRIDA's organisation in github
- Replace `frida-rust`'s dependency on `capstone-rs` with the above.

**Comment by domenukk** [comment] 2023-02-04 17:34
I think it would be even better if we get the needed changes upstreamed, see PR https://github.com/capstone-rust/capstone-rs/pull/140

**Comment by meme** [comment] 2023-02-05 03:00
If we are able to get it upstreamed, that would be preferable, however I am also open to having a fork of capstone-rs inside of the Frida organization, and using it inside of the Frida Rust bindings. Alternatively, we could also maintain the capstone-rs bindings inside of this repository as well as part of the Cargo workspace in the interim.

**Comment by WorksButNotTested** [comment] 2023-02-05 10:35
I’m happy either way. If there’s a long wait for capstone to upstream, it would be great if you’re able to pursue one of the other options as an interim measure.

**Comment by meme** [comment] 2023-02-05 17:49
I wonder if the patch that @domenukk supplied is sufficient, or if we should instead rewrite the Capstone bindings to use the symbols exposed from `frida-gum-sys`? That would ensure that there is _really_ only 1 version of Capstone.

In the meantime I have addressed arm support. Thanks.

**Comment by domenukk** [comment] 2023-02-05 21:07
The patch should be all that's needed, apart from the two todos, see https://github.com/capstone-rust/capstone-rs/pull/140/files#diff-840483b72458d4076f7d2f023cdeefce874a517435c1352a32a974988986c53eR74


I'd advise not to copy the folder into this repo, but to fork the bindings and publish the fork on crates, that way syncing new changes from upstream is less work.
But either way is fine for me

**Comment by WorksButNotTested** [comment] 2023-02-18 15:37
> If we are able to get it upstreamed, that would be preferable, however I am also open to having a fork of capstone-rs inside of the Frida organization, and using it inside of the Frida Rust bindings. Alternatively, we could also maintain the capstone-rs bindings inside of this repository as well as part of the Cargo workspace in the interim.

Seems capstone have reservations about Frida specific changes. https://github.com/capstone-rust/capstone-rs/pull/140#pullrequestreview-1304478930. Are we able to pursue the alternatives?

**Comment by domenukk** [comment] 2023-03-21 15:08
I think frida should vendor its own capstone-rs, as it also vendors its own capstone.

**Comment by oleavr** [comment] 2023-04-14 09:42
> I think frida should vendor its own capstone-rs, as it also vendors its own capstone.

Let's do it. Anyone interested in taking a stab at it?

**Comment by WorksButNotTested** [comment] 2023-04-14 13:10
Most of the hard work should’ve already been done here I think.

https://github.com/domenukk/capstone-rs

Just the repo could do with being moved to FRIDAs organisation and then the dependencies need updating in Frida-rust.

**Comment by domenukk** [comment] 2023-05-05 10:12
The issue is that Frida's capstone added some instructions that are not supported in the upstream capstone bindings (and that they do not plan to add)

**Comment by domenukk** [comment] 2023-05-08 12:31
I don't fully understand, but if you think you have a simpler solution I'm all for it ;)

**Comment by aviramha** [comment] 2023-06-09 15:23
Any update on this?

**Comment by aviramha** [comment] 2023-06-09 16:01
I think I understood @meme idea - implemented here https://github.com/frida/frida-rust/pull/99

**Comment by meme** [comment] 2023-07-05 21:34
Going to close this, as we no longer have a dependency on Capstone (other than the one that's in Frida already) https://github.com/frida/frida-rust/pull/99

**Closed by meme** 2023-07-05 21:34 UTC
